alter table LIBRARY_LIBRARY_CATEGORIES_LINK add constraint FK_LIBCAT_ON_CATEGORIES foreign key (CATEGORIES_ID) references LIBRARY_CATEGORIES(ID);
alter table LIBRARY_LIBRARY_CATEGORIES_LINK add constraint FK_LIBCAT_ON_LIBRARY foreign key (LIBRARY_ID) references LIBRARY_LIBRARY(ID);
